config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#landing'
  resources :locations
  resources :users
  devise_for :admins
  resources :challenges

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/challenge.rb
class Challenge < ActiveRecord::Base
  has_and_belongs_to_many :locations
  has_many :participations
end

app/models/location.rb
class Location < ActiveRecord::Base
  has_and_belongs_to_many :challenges
  has_many :participations
end

app/models/participation.rb
class Participation < ActiveRecord::Base
  belongs_to :user
  belongs_to :challenge
  belongs_to :location

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :participations
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

  before_action :authenticate_admin!
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def after_sign_in_path_for(resource)
    users_path
  end

  def after_sign_out_path_for(resource_or_scope)
    root_path
  end
end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController

  before_action :authenticate_admin!, only: [:index, :new, :create, :edit, :update, :destroy]

  def index
    @challenges = Challenge.all
  end

  def new
    @challenge = Challenge.new
  end

  def show
    @challenge = Challenge.find(params[:id])
    @location = Location.find(params[:location])
  end

  def create
    @challenge = Challenge.new(challenge_params)

    if params[:file].present?
      req = Cloudinary::Uploader.upload(params[:file])
      publicId = req["public_id"]
      @challenge.image_url = publicId
    end

    if @challenge.save

      # TODO: fix this shit
      @challenge.update(location_ids: params[:location_ids].split(','))
      redirect_to challenges_path, notice: "Your challenge was created"
    else
      redirect_to new_challenge_path, notice: "Something went wrong"
    end
  end

  def edit
    @challenge = Challenge.find(params[:id])
  end

  def update
    @challenge = Challenge.find(params[:id])
    @challenge.update_attributes(challenge_params)

    if @challenge.save
      redirect_to challenges_path, notice: "Your challenge was updated"
    else
      redirect_to edit_challenge_path, notice: "Something went wrong"
    end
  end

  def destroy
    @challenge = Challenge.find(params[:id])
    @challenge.destroy

    redirect_to challenges_path, notice: "Your challenge was destroyed"
  end

  private

  def challenge_params
    params.require(:challenge).permit(:name, :image_url)
  end

end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

  def create
    @location = Location.new(location_params)

    if @location.save
      render json: @location
    else
      render json: @location.errors, status: :unprocessable_entity
    end
  end

  private

  def location_params
    params.require(:location).permit(:latitude, :longtitude, :name)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def landing
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!
  def index
   @challenges = Challenge.all.group_by(&:locations)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/admin/index.html.erb
<div class="row">
  <div class="col-md-6">
    <h1>Landing page</h1>
    <p>And Hello World.</p>
  </div>
</div>

<!-- <div id="location"></div>
<div id="mapArea" style="height:500px; width:500px"></div> -->

Destination: <input type="text" id="destination" /><br /><br/>
<div id="floating-panel">
   <b>Mode of Travel: </b>
   <select id="mode">
     <option value="DRIVING">Driving</option>
     <option value="WALKING">Walking</option>
     <option value="BICYCLING">Bicycling</option>
     <option value="TRANSIT">Transit</option>
   </select>
   </div>
<button id="btnPath" onclick="findPath();">Show Path</button>
<div id="mapArea" style="width:600px;height:600px;"></div>
<div id="distance"></div>

app/views/challenges/_form.html.erb
<div id="challenges_form">
  <%= form_for @challenge, :html => {:multipart => true} do |f| %>
    <%if @challenge.errors.any?%>
      <% @challenge.errors.full_messages.each do |msg| %>
        <div class="alert alert-danger"><%= msg %></div>
      <% end %>
    <% end %>

    <%= hidden_field_tag :location_ids %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, required: true, class: 'form-control', autofocus: true %>
    </div>
    <div class="form-group">
      <%= f.label :image_url %>
      <%= cl_image_upload_tag(:image_url) %>
    </div>

    <div class="row">
      <div class="col-xs-6">
        <div id="mapAreaChallengeCreation" style="width:100%; height:555px;"></div>
      </div>
      <div class="col-xs-6">
        <div class="locations">
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-6">
        <%= f.submit class: 'btn btn-primary', id: 'submitChallengeBtn' %>
      </div>
    </div>

  <% end %>
</div>

app/views/challenges/edit.html.erb
<h1>Edit challenge</h1>
<%= render partial: 'form' %>

app/views/challenges/index.html.erb
<div class='row'>
  <div class="col-md-12">
    <%= link_to 'Create new challenge', new_challenge_path, class: "btn btn-lg btn-primary pull-right" %>
    <table class="table table-striped">
      <thead>
        <tr>
          <td><h4 class="lead">Name</h4></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
      </thead>
      <tbody>
        <% @challenges.each do |challenge| %>
          <tr>
            <td><%= challenge.name %></td>
            <td><%= cl_image_tag(challenge.image_url, :crop => :fill, :width => 50, :height => 50) %></td>
            <td></td>
            <td><%= link_to 'Edit', edit_challenge_path(challenge), class: 'btn btn-warning' %></td>
            <td><%= link_to 'Destroy', challenge_path(challenge), method: :delete, data: { confirm: "You sure m8?" }, class: 'btn btn-danger' %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/challenges/new.html.erb
<h1 class="center">New challenge</h1>

<%= render partial: 'form' %>

app/views/challenges/show.html.erb
<div class="challengeShow">
  <div class="row">
    <div class="col-md-6">
      <div id="userChallengeMap" style="width:600px;height:600px;"></div>
      <div id="distance"></div>
    </div>
    <div class="col-md-6" style="text-align:right">
      <div class="locations-name" data-lat="<%= @location.latitude %>" data-lng="<%= @location.longtitude %>">
        <p style="font-weight:bold;" class="loc-name lead"></h3>
      </div>
      You have to go at
      <p id="loc-lat" data-lat='<%=@location.latitude %>' >latitude:<%= @location.latitude %></p>
      <p id="loc-lng" data-lng='<%=@location.longtitude %>' >longtitude:<%= @location.longtitude %></p>
      to make this challenge
    </div>
  </div>
</div>

<div class="modal fade" tabindex="-1" role="dialog" id='winChallengeModal'>
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">YOU WON!</h4>
      </div>
      <div class="modal-body center">
        <div><%= cl_image_tag(@challenge.image_url, :crop => :fill, :width => 480, :height => 480) %></div>
      </div>
      <div class="modal-footer">
        <%= link_to 'Continue', users_path, class: 'btn btn-primary' %>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/layouts/_navbar.html.erb
<!--

    </div>
    <ul class="nav navbar-nav navbar-right">
      <% if current_admin %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Challenges', challenges_path%></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
        <li><%= link_to 'Sign out', destroy_admin_session_path, method: :delete %></li>
      <% end %> -->
      <!-- <% if current_user %>
        <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
      <% end %>
      </ul>
  </div><! /.container-fluid -->
<!-- </nav> -->


<nav role="navigation" class="navbar navbar-inverse">

    <div class="navbar-header">
        <button type="button" data-target="#navbarCollapse" data-toggle="collapse" class="navbar-toggle">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a href="/" class="navbar-brand"><%= image_tag('imageedit_1_8212679445.png', alt: 'brand', class: 'wide')%></a>
    </div>

    <div id="navbarCollapse" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
            <!-- <li class="active"><a href="#">Home</a></li>
            <li><a href="#">Profile</a></li> -->
            <!-- <li class="dropdown">
                <a data-toggle="dropdown" class="dropdown-toggle" href="#">Messages <b class="caret"></b></a> -->
                <ul role="menu" class="dropdown-menu">
                  <% if current_admin %>
                    <!-- <li class="dropdown"> -->
                      <!-- <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a> -->
                        <li><%= link_to 'Challenges', challenges_path%></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="#">Separated link</a></li>
                      </ul>

        </ul>
        <!-- <form role="search" class="navbar-form navbar-left">
            <div class="form-group">
                <input type="text" placeholder="Search" class="form-control">
            </div>
        </form> -->
        <ul class="nav navbar-nav navbar-right">
          <% if current_user %>
            <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
          <% end %>
          <% else %>
            <li><%= link_to 'Sign out', destroy_admin_session_path, method: :delete %></li>

          <% end %>
            <!-- <li><a href="#">Login</a></li> -->
        </ul>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FindIo</title>
  <script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAPS_API_KEY'] %>&libraries=places"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="https://fonts.googleapis.com/css?family=Ubuntu" rel="stylesheet">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</head>
  <body>

    <%= render partial: '/layouts/navbar'  %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <div class="container">
      <%= yield %>
    </div>

  </body>
</html>

app/views/pages/landing.html.erb
<%= video_tag(['Shoes-Stories.mp4', 'Shoes-Stories.webm'], playsinline: true, autoplay: true, muted: true, loop: true, poster: 'Shoes-Stories.jpg', id:"bgvid") %>

<div class="row">
  <div class="col-xs-12">
    <div class="row">
      <div class="col-sm-12">
        <div class="text-center featuretext">
          <p>The world's greatest geolocation website.<br>
          Are you ready to start your journey?</p>
          <% if current_user %>
            <%= link_to 'Get started', users_path, class: "btn btn-primary btn-lg" %>
          <% else %>
            <button type="button" class="btn btn-primary btn-lg text-center fromtop" data-toggle="modal" data-target=".bs-example-modal-sm">Get Started</button>
          <% end %>

          <div class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
            <div class="modal-dialog modal-sm" role="document">
              <div class="modal-landing modal-content">
               Welcome to Find.io <br>
               A place where all your dreams of walking around a city can come true.<br>
               Let's get started by telling us who you are.<hr>
               <%= link_to "Login", user_session_path, class: 'btn btn-large' %>
               <%= link_to "Sign up", new_user_registration_path, class: 'btn btn-large' %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="usersIndex">

    <h1 class="center"></h1>

    <div class="row">
      <div class="col-md-6">
        <div id="usersIndexMap" style="width:100%;"></div>
        <div id="distance"></div>
      </div>
      <div class="col-md-6">
        <div class="center">
          <% @challenges.each do |locations, challenges| %>
            <div class="panel panel-default">
              <div class="panel-heading"><%= challenges.first.name %></div>
                <div class="panel-body">
                  <% locations.each do |location| %>
                    <%= link_to challenge_path(challenges.first, location: location) do %>
                      <div class="locations-name" data-lat="<%= location.latitude %>" data-lng="<%= location.longtitude %>">
                        <h3 class="loc-name lead"></h3>
                      </div>
                    <% end %>
                  <% end %>
                </div>

              </div>
            <% end %>
          </div>
        </div>
    </div>
</div>